name = "Chicago7"
license = "MIT"
licenselink = "https://github.com/akopdev/hugo-theme-chicago7/blob/master/LICENSE"
description = "Chicago7 theme for Hugo"
homepage = "https://github.com/akopdev/hugo-theme-chicago7/"
tags = ["minimal", "blog", "sass", "retro", "monotone", "clean", "personal", "responsive"]
features = ["blog", "sass", "minimal"]
min_version = "0.90.0"

[author]
name = "Akop Kesheshyan"
homepage = "https://akop.dev"
