baseURL: 'http://gohugo.io/'
languageCode: 'en-us'
theme: "hugo-theme-chicago7"

permalinks:
  posts: /posts/:year:month:day

markup:
  highlight:
    style: "bw"

menu:
  header:
  - name: "About"
    url: "about"
    weight: 40

  - name: "Posts"
    url: "posts"
    weight: 30

  - name: "Projects"
    url: "projects"
    weight: 20

  - name: "Home"
    url: "/"
    weight: 10

params:
  author: "Chicago Example"
  social:
  - name: "github"
    url: "https://github.com/gohugoio"
  - name: "linkedin"
    url: "https://www.example.com"
  - name: "email"
    url: "mailto:email@example.com"

